apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-6msn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fduc-tenant/rhtap-demo-app/hacbs-test-project-6msn@sha256:c6597b6ea929b4a6516c4020b4cf9b6422ff212997ef16ee98f67882c749b0b2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
