apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-6msn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-6msn
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-6msn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-6msn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-6msn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fduc-tenant/rhtap-demo-app/hacbs-test-project-6msn@sha256:c6597b6ea929b4a6516c4020b4cf9b6422ff212997ef16ee98f67882c749b0b2
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
